name: Push to huggingface
on: [push]
jobs:
  Sync:
    runs-on: ubuntu-latest
    env:
      HF_HUB_ENABLE_HF_TRANSFER: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to HuggingFace Hub
        uses: osbm/huggingface-login@v0.0.2
        with:
          username: ${{ secrets.HF_USERNAME }}
          key: ${{ secrets.HF_KEY }}
          add_to_git_credentials: true
      - name: Enable hf_transfer
        run: pip install huggingface_hub[hf_transfer]
      - name: Check if logged in
        run: huggingface-cli whoami
      - name: Upload
        run: huggingface-cli upload AlphaSphereDotAI/chatacter . . --repo-type space
