name: Push to huggingface
on: [push]
jobs:
  Sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to HuggingFace Hub
        uses: osbm/huggingface-login@v0.0.2
        with:
          username: ${{ secrets.HF_USERNAME }}
          key: ${{ secrets.HF_KEY }}
          add_to_git_credentials: true
      - name: Check if logged in
        run: |
          huggingface-cli whoami
          huggingface-cli upload AlphaSphereDotAI/chatacher . .
